apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring  # Same namespace as the deployment
spec:
  selector:
    app: grafana  # This should match the labels of the deployment
  ports:
    - port: 80               # The port that the service exposes internally in the cluster
      targetPort: 3000        # Grafana container port
      protocol: TCP
  type: LoadBalancer         # Exposes the service via an external IP address
